CREATE TABLE "user" (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    registration_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_date TIMESTAMPTZ,
    deletion_date TIMESTAMPTZ,
    avatar_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    gdpr_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    gdpr_acceptance_date TIMESTAMPTZ,
    gdpr_version_accepted VARCHAR(40),
    CONSTRAINT chk_user_role CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN'))
);

CREATE TABLE user_preference (
    id_preference BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    theme VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    id_user BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_user_preference_user FOREIGN KEY (id_user) REFERENCES "user" (id_user),
    CONSTRAINT chk_user_preference_theme CHECK (theme IN ('LIGHT', 'DARK', 'SYSTEM'))
);

CREATE TABLE notification (
    id_notification BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    target_link VARCHAR(500),
    id_user BIGINT NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (id_user) REFERENCES "user" (id_user)
);

CREATE TABLE favorite (
    id_favorite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    favorite_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_user BIGINT NOT NULL,
    CONSTRAINT fk_favorite_user FOREIGN KEY (id_user) REFERENCES "user" (id_user),
    CONSTRAINT chk_favorite_type CHECK (favorite_type IN ('TEAM', 'MATCH', 'PLAYER', 'GROUP', 'STADIUM')),
    CONSTRAINT uq_favorite_user_target UNIQUE (id_user, favorite_type, target_id)
);

CREATE TABLE competition (
    id_competition BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    year INTEGER NOT NULL,
    host_countries VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT uq_competition_year UNIQUE (name, year),
    CONSTRAINT chk_competition_dates CHECK (end_date >= start_date)
);

CREATE TABLE competition_phase (
    id_phase BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_type VARCHAR(40) NOT NULL,
    display_order INTEGER NOT NULL,
    id_competition BIGINT NOT NULL,
    CONSTRAINT fk_competition_phase_competition FOREIGN KEY (id_competition) REFERENCES competition (id_competition),
    CONSTRAINT chk_competition_phase_type CHECK (phase_type IN ('GROUP_STAGE', 'ROUND_OF_32', 'ROUND_OF_16', 'QUARTER_FINAL', 'SEMI_FINAL', 'THIRD_PLACE', 'FINAL')),
    CONSTRAINT uq_competition_phase_order UNIQUE (id_competition, display_order)
);

CREATE TABLE competition_group (
    id_group BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    display_order INTEGER NOT NULL,
    id_phase BIGINT NOT NULL,
    CONSTRAINT fk_competition_group_phase FOREIGN KEY (id_phase) REFERENCES competition_phase (id_phase),
    CONSTRAINT uq_competition_group_name UNIQUE (id_phase, name)
);

CREATE TABLE team (
    id_team BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    fifa_code VARCHAR(3) NOT NULL UNIQUE,
    country VARCHAR(120) NOT NULL,
    flag_url VARCHAR(500),
    coach_name VARCHAR(120),
    world_ranking INTEGER
);

CREATE TABLE player (
    id_player BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE,
    position VARCHAR(30) NOT NULL,
    shirt_number INTEGER,
    photo_url VARCHAR(500),
    id_team BIGINT NOT NULL,
    CONSTRAINT fk_player_team FOREIGN KEY (id_team) REFERENCES team (id_team),
    CONSTRAINT chk_player_position CHECK (position IN ('GOALKEEPER', 'DEFENDER', 'MIDFIELDER', 'FORWARD', 'COACH', 'UNKNOWN'))
);

CREATE TABLE team_group (
    id_team_group BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    points INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    draws INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    goals_for INTEGER NOT NULL DEFAULT 0,
    goals_against INTEGER NOT NULL DEFAULT 0,
    goal_difference INTEGER NOT NULL DEFAULT 0,
    ranking INTEGER,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_team BIGINT NOT NULL,
    id_group BIGINT NOT NULL,
    CONSTRAINT fk_team_group_team FOREIGN KEY (id_team) REFERENCES team (id_team),
    CONSTRAINT fk_team_group_group FOREIGN KEY (id_group) REFERENCES competition_group (id_group),
    CONSTRAINT uq_team_group UNIQUE (id_team, id_group)
);

CREATE TABLE stadium (
    id_stadium BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    city VARCHAR(120) NOT NULL,
    country VARCHAR(120) NOT NULL,
    capacity INTEGER,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6)
);

CREATE TABLE football_match (
    id_match BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    home_score INTEGER,
    away_score INTEGER,
    current_minute INTEGER,
    extra_time INTEGER,
    id_home_team BIGINT NOT NULL,
    id_away_team BIGINT NOT NULL,
    id_stadium BIGINT,
    id_phase BIGINT NOT NULL,
    CONSTRAINT fk_football_match_home_team FOREIGN KEY (id_home_team) REFERENCES team (id_team),
    CONSTRAINT fk_football_match_away_team FOREIGN KEY (id_away_team) REFERENCES team (id_team),
    CONSTRAINT fk_football_match_stadium FOREIGN KEY (id_stadium) REFERENCES stadium (id_stadium),
    CONSTRAINT fk_football_match_phase FOREIGN KEY (id_phase) REFERENCES competition_phase (id_phase),
    CONSTRAINT chk_football_match_status CHECK (status IN ('SCHEDULED', 'LIVE', 'HALF_TIME', 'FINISHED', 'POSTPONED', 'CANCELLED')),
    CONSTRAINT chk_football_match_distinct_teams CHECK (id_home_team <> id_away_team)
);

CREATE TABLE team_composition (
    id_composition BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_starting BOOLEAN NOT NULL DEFAULT FALSE,
    formation VARCHAR(30),
    field_position VARCHAR(30),
    id_match BIGINT NOT NULL,
    id_team BIGINT NOT NULL,
    id_player BIGINT NOT NULL,
    CONSTRAINT fk_team_composition_match FOREIGN KEY (id_match) REFERENCES football_match (id_match),
    CONSTRAINT fk_team_composition_team FOREIGN KEY (id_team) REFERENCES team (id_team),
    CONSTRAINT fk_team_composition_player FOREIGN KEY (id_player) REFERENCES player (id_player),
    CONSTRAINT uq_team_composition_player UNIQUE (id_match, id_player)
);

CREATE TABLE match_event (
    id_event BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    minute INTEGER NOT NULL,
    extra_minute INTEGER,
    description VARCHAR(1000),
    id_match BIGINT NOT NULL,
    CONSTRAINT fk_match_event_match FOREIGN KEY (id_match) REFERENCES football_match (id_match),
    CONSTRAINT chk_match_event_type CHECK (event_type IN ('GOAL', 'OWN_GOAL', 'YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION', 'PENALTY', 'VAR', 'INJURY', 'OTHER'))
);

CREATE TABLE event_player (
    id_event BIGINT NOT NULL,
    id_player BIGINT NOT NULL,
    player_event_role VARCHAR(40) NOT NULL,
    PRIMARY KEY (id_event, id_player, player_event_role),
    CONSTRAINT fk_event_player_event FOREIGN KEY (id_event) REFERENCES match_event (id_event),
    CONSTRAINT fk_event_player_player FOREIGN KEY (id_player) REFERENCES player (id_player)
);

CREATE TABLE match_statistics (
    id_statistics BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    possession_home INTEGER,
    possession_away INTEGER,
    shots_home INTEGER,
    shots_away INTEGER,
    shots_on_target_home INTEGER,
    shots_on_target_away INTEGER,
    corners_home INTEGER,
    corners_away INTEGER,
    fouls_home INTEGER,
    fouls_away INTEGER,
    yellow_cards_home INTEGER,
    yellow_cards_away INTEGER,
    red_cards_home INTEGER,
    red_cards_away INTEGER,
    id_match BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_match_statistics_match FOREIGN KEY (id_match) REFERENCES football_match (id_match)
);

CREATE TABLE data_source (
    id_data_source BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    base_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_sync_at TIMESTAMPTZ
);

CREATE TABLE prediction (
    id_prediction BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_win_probability NUMERIC(5, 2) NOT NULL,
    draw_probability NUMERIC(5, 2) NOT NULL,
    away_win_probability NUMERIC(5, 2) NOT NULL,
    predicted_home_score INTEGER,
    predicted_away_score INTEGER,
    confidence_score NUMERIC(5, 2),
    model_name VARCHAR(120) NOT NULL,
    explanation VARCHAR(2000),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_match BIGINT NOT NULL,
    id_data_source BIGINT,
    CONSTRAINT fk_prediction_match FOREIGN KEY (id_match) REFERENCES football_match (id_match),
    CONSTRAINT fk_prediction_data_source FOREIGN KEY (id_data_source) REFERENCES data_source (id_data_source)
);

CREATE TABLE api_synchronization (
    id_synchronization BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    synchronization_status VARCHAR(40) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    message VARCHAR(1000),
    records_processed INTEGER NOT NULL DEFAULT 0,
    id_data_source BIGINT NOT NULL,
    CONSTRAINT fk_api_synchronization_data_source FOREIGN KEY (id_data_source) REFERENCES data_source (id_data_source),
    CONSTRAINT chk_api_synchronization_status CHECK (synchronization_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX idx_player_team ON player (id_team);
CREATE INDEX idx_team_group_group ON team_group (id_group);
CREATE INDEX idx_football_match_phase ON football_match (id_phase);
CREATE INDEX idx_football_match_date ON football_match (match_date);
CREATE INDEX idx_match_event_match ON match_event (id_match);
CREATE INDEX idx_prediction_match ON prediction (id_match);
CREATE INDEX idx_notification_user ON notification (id_user);
